<a href="https://colab.research.google.com/github/AbhiSharma1511/AI-ML-Learning/blob/main/ML/DataProcessing/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv("/content/iris_data.csv")
X = dataset.iloc[: , : -1].values
Y = dataset.iloc[: , -1].values

In [ ]:
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.9 3.2 5.1 1.8]
 [6.  2.7 4.5 1.5]
 [5.5 2.4 3.8 1.1]
 [6.7 3.1 5.6 2.4]
 [5.8 2.7 4.1 1. ]
 [6.3 2.5 5.  1.9]
 [5.  3.6 1.4 0.2]
 [5.1 3.5 nan 0.2]
 [4.9 3.  1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.9 3.2 5.1 1.8]
 [6.  2.7 nan 1.5]
 [nan 2.4 3.8 1.1]
 [6.7 3.1 5.6 2.4]
 [5.8 2.7 4.1 1. ]
 [6.3 nan 5.  1.9]
 [5.  3.6 1.4 0.2]]
['setosa' 'setosa' 'versicolor' 'virginica' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'virginica' 'setosa' 'setosa' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor' nan 'versicolor'
 'virginica' 'setosa']


### taking care of missing data

In [ ]:
### here we will fill the empty value with the mean in the X dataset
from sklearn.impute import SimpleImputer
imputer  = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])

In [ ]:
print(X)

[[5.1        3.5        1.4        0.2       ]
 [4.9        3.         1.4        0.2       ]
 [6.2        2.9        4.3        1.3       ]
 [5.9        3.2        5.1        1.8       ]
 [6.         2.7        4.5        1.5       ]
 [5.5        2.4        3.8        1.1       ]
 [6.7        3.1        5.6        2.4       ]
 [5.8        2.7        4.1        1.        ]
 [6.3        2.5        5.         1.9       ]
 [5.         3.6        1.4        0.2       ]
 [5.1        3.5        3.73888889 0.2       ]
 [4.9        3.         1.4        0.2       ]
 [6.2        2.9        4.3        1.3       ]
 [5.9        3.2        5.1        1.8       ]
 [6.         2.7        3.73888889 1.5       ]
 [5.75263158 2.4        3.8        1.1       ]
 [6.7        3.1        5.6        2.4       ]
 [5.8        2.7        4.1        1.        ]
 [6.3        2.98421053 5.         1.9       ]
 [5.         3.6        1.4        0.2       ]]


In [ ]:
### here we will fill the empty value with the mean in the Y dataset
from sklearn.impute import SimpleImputer
imputer  = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
Y = Y.reshape(-1,1)
#imputer.fit(Y[:])
#Y[:] = imputer.transform(Y[:])
Y = imputer.fit_transform(Y)

In [ ]:
print(Y)

[['setosa']
 ['setosa']
 ['versicolor']
 ['virginica']
 ['versicolor']
 ['versicolor']
 ['virginica']
 ['versicolor']
 ['virginica']
 ['setosa']
 ['setosa']
 ['setosa']
 ['versicolor']
 ['virginica']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['versicolor']
 ['virginica']
 ['setosa']]


# Encoding categorial data

## encoding the dependent variable


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

specie = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])] , remainder='passthrough')
Y = np.array(specie.fit_transform(Y))

In [ ]:
print(Y)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]]


## encode the independent variables

we did not need to encode as all the independent variables are in numberic form

In [ ]:
# for binary outcome like label encoder we will use the below code
# from sklearn.preprocessing import LableEncoder
# le = LabelEncoder()
# y = np.fit_transform(Y)