In [3]:
import tensorflow as tf

In [4]:
t0_dim = tf.constant(4)
print(t0_dim)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
t1_dim = tf.constant([1,2,3,4], dtype=tf.float32)
print(t1_dim)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [6]:
t2_dim = tf.constant([
    [1,2,3,4],
    [5,6,7,8]
])
print(t2_dim)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [7]:
t3_dim = tf.constant(
    [
        [
        [1,2,3,4],
        [5,6,7,8]
      ],
      [
        [1,2,3,4],
        [5,6,7,8]
      ],
     ]

)
print(t3_dim)

tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]], shape=(2, 2, 4), dtype=int32)


In [8]:
t4_dim = tf.constant(
    [
        [
        [
        [1,2,3,4],
        [5,6,7,8]
      ],
      [
        [1,2,3,4],
        [5,6,7,8]
      ],
     ],
        [
        [
        [1,2,3,4],
        [5,6,7,8]
      ],
      [
        [1,2,3,4],
        [5,6,7,8]
      ],
     ]
    ]
)

print(t4_dim)

tf.Tensor(
[[[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]


 [[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]], shape=(2, 2, 2, 4), dtype=int32)


In [9]:
print(t4_dim.shape)

(2, 2, 2, 4)


In [10]:
print(t4_dim.dtype)

<dtype: 'int32'>


In [11]:
tensor_string  = tf.constant(["hello world", "hi", "I am king"])
print(tensor_string)


tf.Tensor([b'hello world' b'hi' b'I am king'], shape=(3,), dtype=string)


In [12]:
import numpy as np
np_array = np.array([1,2,3,4,5,6])
print(np_array)

[1 2 3 4 5 6]


In [13]:
converted_tensor = tf.convert_to_tensor(np_array);
print(converted_tensor)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int64)


In [20]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [24]:
eye_tensor1 = tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor1)

tf.Tensor(
[[ True False False False]
 [False  True False False]
 [False False  True False]], shape=(3, 4), dtype=bool)


In [17]:
4

4

In [27]:
eye_tensor1 = tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=[2,2],
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor1)

tf.Tensor(
[[[[ True False False False]
   [False  True False False]
   [False False  True False]]

  [[ True False False False]
   [False  True False False]
   [False False  True False]]]


 [[[ True False False False]
   [False  True False False]
   [False False  True False]]

  [[ True False False False]
   [False  True False False]
   [False False  True False]]]], shape=(2, 2, 3, 4), dtype=bool)


In [34]:
fill_tensor = tf.fill(
    [3,2,2,4], 5, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[[[5 5 5 5]
   [5 5 5 5]]

  [[5 5 5 5]
   [5 5 5 5]]]


 [[[5 5 5 5]
   [5 5 5 5]]

  [[5 5 5 5]
   [5 5 5 5]]]


 [[[5 5 5 5]
   [5 5 5 5]]

  [[5 5 5 5]
   [5 5 5 5]]]], shape=(3, 2, 2, 4), dtype=int32)
